#!/bin/bash

set -e

if [[ -n "${OSM_EXTRACTION_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n "Usage: $(basename "$0")

Run linters on the project's code
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        # Lint Bash scripts
        if which shellcheck > /dev/null; then
            shellcheck scripts/*
        fi

        pushd ./src

        # Lint JavaScript
        yarn run lint

        popd
    fi
fi
