#!/bin/bash

set -e

if [[ -n "${OSM_EXTRACTION_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n "Usage: $(basename "$0")

Starts webpack dev server.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        pushd ./src

        yarn run dev-server

        popd
    fi
fi
