#!/bin/bash

set -e

if [[ -n "${OSM_EXTRACTION_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
         "Usage: $(basename "$0")
Run linters and tests."
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        pushd ./src

        #yarn run test

        popd
    fi
fi
