#!/bin/bash

set -e

if [[ -n "${OSM_EXTRACTION_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n "Usage: $(basename "$0")

Builds and pulls container images using docker-compose.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        pushd ./src

        # Install NPM modules
        yarn

        popd
    fi
fi
